<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net11.0-android;net11.0-ios</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net11.0-windows10.0.19041.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>Appostazja.Maui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<IsAotCompatible>true</IsAotCompatible>
		<PublishAot Condition="'$(Configuration)' == 'Release' And $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">true</PublishAot>
		<PublishAot Condition="'$(Configuration)' == 'Release' And $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">true</PublishAot>
		<EnablePreviewFeatures Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">true</EnablePreviewFeatures>
		<!-- Display name -->
		<ApplicationTitle>Appostazja</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>app.apostazja.siostra</ApplicationId>
		<ApplicationIdGuid>aa00049f-af3a-4ec7-9a05-253c223b95d4</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

    <MauiVersion>11.0.0-preview.7.26406.9</MauiVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.5</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
	  <UseMaterial3>true</UseMaterial3>
	  <GoogleMapsApiKey Condition="'$(GoogleMapsApiKey)' == ''">AIzaSyCnGd0QpjRVUrwBQNS-_Xd0gMNRbCEgKJA</GoogleMapsApiKey>
	  <AndroidManifestPlaceholders>GOOGLE_MAPS_API_KEY=$(GoogleMapsApiKey)</AndroidManifestPlaceholders>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appostazja_background.svg" ForegroundFile="Resources\AppIcon\appostazja_icon.svg" Color="#363636" />

		<!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\appostazja_splash.svg" Color="#363636" BaseSize="128,128" />

    <!-- Images -->
		<!--<MauiImage Include="Resources\Images\*" />-->
    <MauiImage Include="Resources\Images\drawing.svg" BaseSize="48,48" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
    <MauiAsset Include="Resources\Fonts\Nunito-Regular.ttf" LogicalName="PdfNunito-Regular.ttf" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="CommunityToolkit.Maui" Version="15.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Maui.Controls.Maps" Version="$(MauiVersion)" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Platforms\Android\Services\" />
	  <Folder Include="Resources\Fonts\" />
	  <Folder Include="Resources\Raw\" />
	  <Folder Include="Resources\Splash\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Appostazja.Core\Appostazja.Core.csproj" />
	</ItemGroup>

	<ProjectExtensions><VisualStudio><UserProperties XamarinHotReloadDebuggerTimeoutExceptionAppostazjaMauiHideInfoBar="True" /></VisualStudio></ProjectExtensions>

</Project>
