<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0-android</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <JavaDocJar Include="Jars\android-maps-utils-3.8.2-javadoc.jar" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.Collection.Ktx" Version="1.4.5.2" />
    <PackageReference Include="Xamarin.GooglePlayServices.Maps" Version="119.1.0" />
  </ItemGroup>
</Project>